trigger:
- azure

pool:
    vmImage: 'ubuntu-latest'

variables:
  ACR_NAME: 'crsanyi'
  IMAGE_NAME: 'mywebapp:v1'
  IMAGE_REPOSITORY: 'crsanyi.azurecr.io/mywebapp:v1'
  TAG: 'crsanyi.azurecr.io/mywebapp:v1'

stages:
- stage: BuildApp
  jobs:
  - job: BuildPushImage
    steps: 
    - task: AzureCLI@2
      displayName: 'Build and push Docker image'
      inputs:
        azureSubscription: 'ZEISSgroup-DI05-ASM-Learning'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        addSpnToEnvironment: true
        inlineScript: |
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME -f Dockerfile .
          az acr login --name $ACR_NAME
          docker tag $IMAGE_NAME $ACR_NAME.azurecr.io/$IMAGE_NAME
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME

- stage: DeployDev
  jobs:
  - job: DeployDev
    steps:
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'ZEISSgroup-DI05-ASM-Learning'
        appType: 'webAppContainer'
        WebAppName: 'sanyilinuxwebappcon'
        DockerNamespace: 'crsanyi'
        DockerRepository: '($IMAGE_REPOSITORY)'
        DockerImageTag: '($TAG)'