trigger:
- azure

pool:
    vmImage: 'ubuntu-latest'

stages:
- stage: BuildApp
  jobs:
  - job: BuildPushImage
    steps: 
    - task: AzureCLI@2
      displayName: 'Build and push Docker image'
      inputs:
        azureSubscription: 'ZEISSgroup-DI05-ASM-Learning'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        addSpnToEnvironment: true
        inlineScript: |
          ACR_NAME=crSanyi
          IMAGE_NAME=mywebapp:v1
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME -f Dockerfile .
          az login
          az acr login --name $ACR_NAME
          docker tag $IMAGE_NAME $ACR_NAME.azurecr.io/$IMAGE_NAME
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME